// views.js — all workspace views
import{DB,Session,esc,uid,ls,getSettings,saveSettings,audit,notify,nowISO}from'./core.js';
import* as E from'./engines.js';import* as P from'./platforms.js';import{toast,openModal,closeModal,setOrgCache,$}from'./ui.js';
export const fld=(schema,data)=>schema.map(([k,l,req,type,opts])=>{const v=data[k]??'';const id='f_'+k;const h=type==='textarea'?`<textarea id="${id}" name="${k}" rows="3">${esc(v)}</textarea>`:type==='select'?`<select id="${id}" name="${k}">${(opts||[]).map(o=>`<option ${o===v?'selected':''}>${o}</option>`).join('')}</select>`:`<input id="${id}" name="${k}" type="${type||'text'}" value="${esc(v)}" ${type==='number'?'step=any':''}>`;return`<label for="${id}">${l}${req?' <span class="req">*</span>':''}</label>${h}`}).join('');
export async function saveMedia(file){const id=uid();const buf=await file.arrayBuffer();
 await DB.put('media',{id,blob:new Blob([buf],{type:file.type}),mime:file.type,name:file.name,ts:nowISO()});return{id}}
export async function mediaURL(id){const m=await DB.get('media',id);return m?URL.createObjectURL(m.blob):null}
// ---------- AI provider abstraction ----------
async function aiChat(org,prompt,json){const s=await getSettings();const sys='You are the Tradestack Marketing Agent. Ground every claim in the BUSINESS KNOWLEDGE provided. Never invent prices, certifications, testimonials, statistics, guarantees. '+((org.brand&&(org.brand.avoidWords||''))?('Avoid words: '+org.brand.avoidWords+'.'):'')+(json?' Respond ONLY with valid JSON {hook,caption,hashtags:[],cta}.':'');
 const kb=retrieve(org,prompt,4).map(r=>r.text).join('\n---\n');
 const messages=[{role:'system',content:sys+'\nBUSINESS KNOWLEDGE:\n'+kb},{role:'user',content:prompt}];
 if(s.ai.provider==='ollama'){const r=await fetch(s.ai.ollamaUrl+'/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:s.ai.model,messages,stream:false,format:json?'json':undefined})});if(!r.ok)throw new Error('ollama');const j=await r.json();return j.message.content}
 if(s.ai.provider==='compat'){const r=await fetch(s.ai.compatUrl,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+s.ai.compatKey},body:JSON.stringify({model:s.ai.compatModel,messages})});if(!r.ok)throw new Error('compat');const j=await r.json();return j.choices[0].message.content}
 return null}
export function retrieve(org,q,k){const corpus=[];const b=org.business||{};
 Object.entries(b).forEach(([key,v])=>v&&corpus.push({src:'business.'+key,text:key+': '+v}));
 (org.products||[]).forEach(p=>corpus.push({src:'product',text:`Product ${p.name}: ${p.description||''} benefits:${p.benefits||''} price:${p.price||'n/a'} claims:${p.allowedClaims||''}`}));
 (org.ctas||[]).forEach(c=>corpus.push({src:'cta',text:`CTA ${c.text}: ${c.value}`}));
 const t=E.tok(q);return corpus.map(c=>({c,s:c.text.toLowerCase(),n:t.filter(w=>c.text.toLowerCase().includes(w)).length})).filter(x=>x.n>0).sort((a,b)=>b.n-a.n).slice(0,k).map(x=>x.c)}
async function genContent(org,params){let note='';let out=null;
 try{const raw=await aiChat(org,`Write ${params.platform} ${params.pillar} content. Topic: ${params.topic||'your expertise'}. Product: ${(params.product&&params.product.name)||'none'}. Tone: ${params.tone}. Objective: ${params.objective}. CTA: ${params.cta?params.cta.text+' '+params.cta.value:''}. Length: ${params.length||'medium'}.`,true);
  out=JSON.parse(raw)}catch(e){out=null}
 if(!out){out=E.offlineGenerate(org,params);note='Generated by the built-in offline rules engine (no AI provider reachable).'}
 const comp=E.complianceCheck(out.caption,params.platform,out.hashtags);
 const rep=E.repetitionCheck(out.caption,await DB.recs('schedule',Session.orgId));
 return{out,comp,rep,note}}
// ---------- STUDIO ----------
export async function studio(el,pref){const org=window.__org;const prods=org.products||[];const ctas=org.ctas||[];
 const p=Object.assign({platform:'facebook',objective:'awareness',pillar:'Education',tone:(org.brand&&org.brand.tone)||'professional',length:'medium'},pref||{});
 el.innerHTML=`<h1>Content Studio</h1><div class="grid g2"><div class="card"><h3>Brief</h3>
 <label>Platform</label><select id="s_pf">${Object.keys(P.PLATFORMS).map(k=>`<option ${k===p.platform?'selected':''}>${k}</option>`).join('')}</select>
 <label>Objective</label><select id="s_ob">${['awareness','traffic','leads','sales','community'].map(o=>`<option ${o===p.objective?'selected':''}>${o}</option>`).join('')}</select>
 <label>Product/service</label><select id="s_pr"><option value="">—</option>${prods.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join('')}</select>
 <label>Pillar</label><select id="s_pi">${['Education','Product','Problem','Proof','Story','Promotional','FAQ'].map(o=>`<option ${o===p.pillar?'selected':''}>${o}</option>`).join('')}</select>
 <label>Topic / trend</label><input id="s_tp" value="${esc(p.topic||'')}">
 <label>Tone</label><select id="s_tn">${['professional','friendly','bold','playful','empathetic'].map(o=>`<option ${o===p.tone?'selected':''}>${o}</option>`).join('')}</select>
 <label>CTA (auto if blank)</label><select id="s_cta"><option value="">Auto</option>${ctas.map((c,i)=>`<option value="${i}">${esc(c.text)}</option>`).join('')}</select>
 <label>Audience</label><input id="s_aud" value="${esc((org.marketing&&org.marketing.targetAudience)||'')}">
 <div style="margin-top:10px"><button class="gold" id="s_gen">Generate</button></div></div>
 <div class="card"><h3>Result</h3><div id="s_out"><p class="muted">Content, visual, compliance and publishing appear here side-by-side.</p></div></div></div>`;
 $('#s_gen').onclick=async e=>{e.target.disabled=true;e.target.textContent='Generating…';
  const params={platform:$('#s_pf').value,objective:$('#s_ob').value,pillar:$('#s_pi').value,tone:$('#s_tn').value,topic:$('#s_tp').value,audience:$('#s_aud').value,length:'medium',
   product:prods[+$('#s_pr').value]||null,cta:$('#s_cta').value===''?autoCTA(org,$('#s_ob').value):ctas[+$('#s_cta').value]};
  const r=await genContent(org,params);renderResult(r,params);e.target.disabled=false;e.target.textContent='Generate'};
 function autoCTA(org,ob){const c=org.ctas||[];const m={sales:['order','whatsapp'],leads:['whatsapp','email','booking'],traffic:['website'],awareness:['website'],community:['whatsapp']}[ob]||[];
  for(const k of m){const f=c.find(x=>x.kind===k);if(f)return f}return c[0]||null}
 function renderResult(r,params){window.__last={r,params};
  $('#s_out').innerHTML=`${r.note?`<p class="warn">${esc(r.note)}</p>`:''}
  <div class="grid g2"><div><h3>Content</h3><label>Hook</label><textarea id="r_hk" rows="2">${esc(r.out.hook||'')}</textarea><button class="small" id="r_rehook">Regenerate hook</button>
  <label>Caption</label><textarea id="r_cap" rows="8">${esc(r.out.caption||'')}</textarea><button class="small" id="r_recap">Regenerate caption</button>
  <label>Hashtags</label><input id="r_hs" value="${esc((r.out.hashtags||[]).join(', '))}"><button class="small" id="r_rehs">Regenerate hashtags</button>
  <label>CTA</label><input id="r_cta" value="${esc(params.cta?(params.cta.text+': '+params.cta.value):'')}"></div>
  <div><h3>Visual</h3><div id="r_vis"></div>
  <h3>Compliance</h3><span class="pill ${r.comp.level}">${r.comp.level.toUpperCase()}</span> <span class="muted">score ${r.comp.score}</span>
  <ul>${r.comp.issues.map(i=>`<li class="${i.level}">${esc(i.msg)}</li>`).join('')||'<li class="ok">No issues detected.</li>'}</ul>
  ${r.comp.rewrite?`<button class="small ghost" id="r_rw">Apply safer rewrite</button>`:''}
  ${r.rep.warn?`<p class="warn">⚠ ${esc(r.rep.msg)}</p>`:''}
  <h3>Publishing</h3><label>Schedule at</label><input type="datetime-local" id="r_when" value="${defWhen()}">
  <div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:8px"><button id="r_save">Save draft</button><button class="gold" id="r_sched">Approve & Schedule</button><button class="red" id="r_pub">Publish now</button></div></div></div>`;
  visualPane(params);
  $('#r_rehook').onclick=async()=>{const o=E.offlineGenerate(org,params);$('#r_hk').value=o.hook};
  $('#r_recap').onclick=async()=>{const o=E.offlineGenerate(window.__org,Object.assign({},params,{topic:params.topic||$('#s_tp').value}));$('#r_cap').value=o.caption};
  $('#r_rehs').onclick=()=>{$('#r_hs').value=E.hashtagSets(org,{product:params.product,topic:params.topic},params.platform).flat.join(', ')};
  const rw=$('#r_rw');if(rw)rw.onclick=()=>{$('#r_cap').value=r.comp.rewrite;toast('Safer rewrite applied','ok')};
  const collect=()=>Object.assign({},r.out,{hook:$('#r_hk').value,caption:$('#r_cap').value,hashtags:$('#r_hs').value.split(',').map(s=>s.trim().replace(/^#/,'')).filter(Boolean)});
  $('#r_save').onclick=async()=>{await DB.putRec('schedule',Session.orgId,base(params,collect(),'draft'));toast('Draft saved','ok');await setOrgCache()};
  $('#r_sched').onclick=async()=>{const c=E.complianceCheck($('#r_cap').value,params.platform,collect().hashtags);
   if(c.level==='blocked')return toast('Blocked by compliance engine.','err');
   await DB.putRec('schedule',Session.orgId,base(params,collect(),'needs_review',$('#r_when').value));toast('Sent to approval queue','ok');await setOrgCache()};
  $('#r_pub').onclick=async()=>{const id=await DB.putRec('schedule',Session.orgId,base(params,collect(),'approved',$('#r_when').value));
   const post=await DB.get('records',id);await publishFlow(post)};}
 function base(params,content,status,when){return{platform:params.platform,pillar:params.pillar,topic:params.topic,objective:params.objective,product:params.product?params.product.name:null,cta:params.cta?params.cta.text+' '+(params.cta.value||''):null,hook:content.hook,caption:content.caption,hashtags:content.hashtags,status,scheduledAt:when?new Date(when).toISOString():new Date(Date.now()+3600e3).toISOString(),createdAt:nowISO()}}
 function defWhen(){const d=new Date(Date.now()+86400e3);d.setMinutes(0);return d.toISOString().slice(0,16)}
 async function visualPane(params){const br=(window.__org.brand)||{};
  $('#r_vis').innerHTML=`<p class="muted">${P.PLATFORMS[params.platform].auto?'Auto-publish supports text/link; attach image for full post.':'Visual optional for text posts.'}</p>
  <button class="small gold" id="r_compose">Create branded visual (free, in-browser)</button> <button class="small ghost" id="r_brief">Design brief</button> <button class="small ghost" id="r_up">Upload image</button><input type="file" id="r_upf" accept="image/*" hidden><div id="r_prev" style="margin-top:8px"></div>`;
  $('#r_compose').onclick=()=>composeModal(params);
  $('#r_brief').onclick=()=>{const b=E.visualBrief(window.__org,params,params.product,$('#r_hk').value);openModal('Visual design brief',`<p><b>Concept:</b> ${esc(b.concept)}</p><p><b>Dimensions:</b> ${b.dims[0]}×${b.dims[1]}px</p><p><b>Text on visual:</b> ${esc(b.textOnVisual)}</p><p><b>Colours:</b> ${esc(b.colors)}</p><p><b>Logo:</b> ${esc(b.logo)}</p><p><b>Product:</b> ${esc(b.product)}</p><p><b>CTA on visual:</b> ${esc(b.ctaOnVisual)}</p><p><b>Style:</b> ${esc(b.style)} · Export PNG</p>`)};
  $('#r_up').onclick=()=>$('#r_upf').click();$('#r_upf').onchange=async e=>{const m=await saveMedia(e.target.files[0]);window.__lastMedia=m.id;$('#r_prev').innerHTML=`<img src="${await mediaURL(m.id)}" style="max-width:140px;border-radius:8px" alt="uploaded visual">`}}
}
export function composeModal(params){openModal('Brand Visual Composer',`<label>Headline</label><input id="c_h" value="${esc(params.topic||'')}"><label>Sub-text</label><input id="c_s" value="${esc((window.__org.business||{}).slogan||'')}"><label>CTA chip</label><input id="c_c" value="${esc(params.cta?params.cta.text:'')}"><label>Ratio</label><select id="c_r"><option value="instagram_square">IG square</option><option value="instagram_portrait">IG portrait</option><option value="story">Story/Reel</option><option value="facebook">Facebook</option><option value="x">X</option><option value="pinterest">Pinterest</option><option value="youtube">YouTube</option></select><div style="margin-top:10px"><button class="gold" id="c_go">Render PNG</button> <button id="c_dl" hidden>Download</button></div><canvas id="c_cv" style="max-width:100%;margin-top:10px;border-radius:8px"></canvas>`,()=>{
 $('#c_go').onclick=async()=>{const br=window.__org.brand||{};const d=E.DIMS[$('#c_r').value]||[1080,1080];const cv=$('#c_cv');cv.width=d[0]/2;cv.height=d[1]/2;const x=cv.getContext('2d');
  const g=x.createLinearGradient(0,0,cv.width,cv.height);g.addColorStop(0,(br.colours&&br.colours.primary)||'#0e2a5c');g.addColorStop(1,'#123a7d');x.fillStyle=g;x.fillRect(0,0,cv.width,cv.height);
  x.fillStyle=(br.colours&&br.colours.secondary)||'#c9a227';x.fillRect(0,cv.height-14,cv.width,14);
  x.fillStyle='#fff';x.font='bold '+Math.round(cv.width/14)+'px Segoe UI';wrap(x,$('#c_h').value,cv.width*0.08,cv.height*0.3,cv.width*0.84,Math.round(cv.width/12));
  x.font=Math.round(cv.width/26)+'px Segoe UI';x.fillStyle='#e6c15c';x.fillText(($('#c_s').value||'').slice(0,60),cv.width*0.08,cv.height*0.72);
  if($('#c_c').value){x.fillStyle='#d21f2b';const w2=x.measureText($('#c_c').value).width+30;x.fillRect(cv.width*0.08,cv.height*0.8,w2,34);x.fillStyle='#fff';x.fillText($('#c_c').value,cv.width*0.08+15,cv.height*0.8+24)}
  const url=cv.toDataURL('image/png');$('#c_dl').hidden=false;$('#c_dl').onclick=()=>{const a=document.createElement('a');a.href=url;a.download='tradestack-visual.png';a.click()};
  const b=await(await fetch(url)).blob();const m=await saveMedia(new File([b],'visual.png',{type:'image/png'}));window.__lastMedia=m.id;toast('Saved to Media Library','ok')}})}
function wrap(x,t,mx,my,mw,lh){const w=String(t||'').split(' ');let y=my,line='';for(const s of w){if(x.measureText(line+s).width>mw){x.fillText(line,mx,y);y+=lh;line=s+' '}else line+=s+' '}x.fillText(line,mx,y)}
// ---------- publish flow (manual assistant for non-auto platforms) ----------
export async function publishFlow(post){const pf=post.data.platform;
 if(pf==='facebook'){const conns=await DB.recs('connection',Session.orgId);const conn=conns.find(c=>c.status==='connected');
  if(conns.length&&conn){try{const id=await P.metaPublish(conn,post.data.caption+'\n\n'+(post.data.hashtags||[]).map(h=>'#'+h).join(' '));
   await DB.putRec('schedule',Session.orgId,Object.assign(post.data,{status:'published',externalId:id,publishedAt:nowISO()}),post.id);toast('Published to Facebook ✔','ok');await audit(Session.orgId,'publish',id);return}
   catch(e){await DB.putRec('schedule',Session.orgId,Object.assign(post.data,{status:'failed',lastError:String(e.message)}),post.id);toast('Facebook publishing failed. Your content remains saved. Reconnect or retry.','err');return}}
  return manualModal(post)}
 return manualModal(post)}
function manualModal(post){const pf=post.data.platform;const txt=post.data.caption+'\n\n'+(post.data.hashtags||[]).map(h=>'#'+h).join(' ');
 const wa=(window.__org.business||{}).whatsapp;
 openModal('Publish to '+P.PLATFORMS[pf].name,`<p class="muted">${esc(P.PLATFORMS[pf].note)}</p><textarea rows="8" id="m_txt">${esc(txt)}</textarea>
 ${pf==='whatsapp'&&wa?`<p><a class="btn" target="_blank" href="https://wa.me/${esc(wa.replace(/\D/g,''))}?text=${encodeURIComponent(txt.slice(0,800))}">Open WhatsApp with message</a></p>`:`<p><a class="btn" target="_blank" href="${P.OPENURL[pf]}">Open ${P.PLATFORMS[pf].name}</a></p>`}
 <p><button id="m_copy">Copy content</button> <button class="ghost" id="m_exp">Export .txt</button></p>
 <label>After posting, paste post URL (optional)</label><input id="m_url"><p><button class="gold" id="m_done">Mark as published</button></p>`,()=>{
 $('#m_copy').onclick=async()=>{await navigator.clipboard.writeText($('#m_txt').value);toast('Copied','ok')};
 $('#m_exp').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([$('#m_txt').value],{type:'text/plain'}));a.download='post.txt';a.click()};
 $('#m_done').onclick=async()=>{await P.markPublished(Session.orgId,post,$('#m_url').value);closeModal();toast('Recorded as published','ok');await setOrgCache()}})}
// ---------- CALENDAR ----------
export async function calendar(el){const posts=await DB.recs('schedule',Session.orgId);const now=new Date();const y=now.getFullYear(),m=now.getMonth();
 const first=new Date(y,m,1);const start=(first.getDay()+6)%7;const days=new Date(y,m+1,0).getDate();
 let cells='<div class="cal">'+['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<div class="d h">${d}</div>`).join('');
 for(let i=0;i<start;i++)cells+='<div class="d"></div>';
 for(let d=1;d<=days;d++){const list=posts.filter(p=>{const t=new Date(p.scheduledAt);return t.getDate()===d&&t.getMonth()===m&&t.getFullYear()===y});
  cells+=`<div class="d" data-day="${d}"><b>${d}</b>${list.map(p=>`<div class="item ${p.status==='published'?'gold':p.status==='failed'?'red':''}" draggable="true" data-id="${p.id}" title="${esc(p.status)}">${esc(P.PLATFORMS[p.platform].name)} · ${esc((p.hook||p.topic||'').slice(0,18))}</div>`).join('')}</div>`}
 el.innerHTML=`<h1>Content Calendar</h1><div class="card"><button class="gold" id="plan30">Generate 30-Day Content Plan</button> <a class="btn ghost" href="#/studio">New content</a><span class="muted" style="margin-left:8px">Drag cards to reschedule.</span></div><div class="card">${cells}</div><div class="card"><h3>Approval queue</h3><table><tr><th>Post</th><th>Platform</th><th>When</th><th>Status</th><th>Actions</th></tr>${posts.filter(p=>['needs_review','due','failed'].includes(p.status)).map(p=>`<tr><td>${esc((p.hook||'').slice(0,60))}<br><span class="tiny muted">${esc((p.caption||'').slice(0,80))}</span></td><td>${p.platform}</td><td class="tiny">${new Date(p.scheduledAt).toLocaleString()}</td><td><span class="pill st-${p.status}">${p.status}</span></td><td><button class="small" data-ap="${p.id}">Approve</button> <button class="small ghost" data-ed="${p.id}">Edit</button> <button class="small red" data-rj="${p.id}">Reject</button> ${p.status!=='needs_review'?`<button class="small gold" data-pb="${p.id}">Publish</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">Queue empty.</td></tr>'}</table></div>`;
 $('#plan30').onclick=async()=>{const plan=E.buildPlan(window.__org,posts,30);let n=0;
  for(const s of plan){const params={platform:s.platform,pillar:s.pillar,topic:s.topic,tone:(window.__org.brand||{}).tone||'professional',product:(window.__org.products||[])[0]||null,cta:(window.__org.ctas||[])[0]||null};
   const r=await genContent(window.__org,params);
   await DB.putRec('schedule',Session.orgId,{platform:s.platform,pillar:s.pillar,topic:s.topic,hook:r.out.hook,caption:r.out.caption,hashtags:r.out.hashtags,cta:params.cta?params.cta.text:null,status:'needs_review',scheduledAt:s.scheduledAt,createdAt:nowISO()});n++}
  toast(n+' drafts created for review','ok');calendar(el)};
 el.querySelectorAll('.item').forEach(it=>{it.ondragstart=e=>e.dataTransfer.setData('text',it.dataset.id)});
 el.querySelectorAll('.d[data-day]').forEach(d=>{d.ondragover=e=>e.preventDefault();d.ondrop=async e=>{e.preventDefault();const id=e.dataTransfer.getData('text');const p=await DB.get('records',id);const t=new Date(p.data.scheduledAt);t.setMonth(m);t.setDate(+d.dataset.day);
  await DB.putRec('schedule',Session.orgId,Object.assign(p.data,{scheduledAt:t.toISOString()}),id);await audit(Session.orgId,'reschedule',id);calendar(el)}});
 el.querySelectorAll('[data-ap]').forEach(b=>b.onclick=async()=>{const p=await DB.get('records',b.dataset.ap);await DB.putRec('schedule',Session.orgId,Object.assign(p.data,{status:'scheduled'}),p.id);toast('Approved & scheduled','ok');calendar(el)});
 el.querySelectorAll('[data-rj]').forEach(b=>b.onclick=async()=>{const p=await DB.get('records',b.dataset.rj);await DB.putRec('schedule',Session.orgId,Object.assign(p.data,{status:'rejected'}),p.id);calendar(el)});
 el.querySelectorAll('[data-pb]').forEach(b=>b.onclick=async()=>{const p=await DB.get('records',b.dataset.pb);await publishFlow(p);calendar(el)});
 el.querySelectorAll('[data-ed]').forEach(b=>b.onclick=async()=>{const p=await DB.get('records',b.dataset.ed);openModal('Edit post',`<label>Caption</label><textarea id="e_c" rows="6">${esc(p.data.caption)}</textarea><label>Scheduled</label><input type="datetime-local" id="e_w" value="${p.data.scheduledAt.slice(0,16)}"><p><button class="gold" id="e_s">Save</button></p>`,()=>{$('#e_s').onclick=async()=>{await DB.putRec('schedule',Session.orgId,Object.assign(p.data,{caption:$('#e_c').value,scheduledAt:new Date($('#e_w').value).toISOString()}),p.id);closeModal();calendar(el)}})})}
// ---------- TRENDS ----------
const PROXIES=[u=>'https://api.allorigins.win/raw?url='+encodeURIComponent(u),u=>'https://corsproxy.io/?url='+encodeURIComponent(u)];
async function fetchFeed(url){for(const px of[ u=>u,...PROXIES]){try{const r=await fetch(px(url));if(!r.ok)continue;const t=await r.text();const doc=new DOMParser().parseFromString(t,'text/xml');
 const items=[...doc.querySelectorAll('item,entry')].slice(0,15).map(it=>({title:(it.querySelector('title')||{}).textContent||'',link:(it.querySelector('link')||{}).textContent||(it.querySelector('link')||{getAttribute:()=>''}).getAttribute&&it.querySelector('link').getAttribute('href')||'',date:(it.querySelector('pubDate,updated,published')||{}).textContent||new Date().toISOString(),source:url.replace(/https?:\/\//,'').slice(0,24)})).filter(i=>i.title);
 if(items.length)return items}catch(e){}}return[]}
export async function trends(el){el.innerHTML=`<h1>Trends</h1><div class="card"><button class="gold" id="t_scan">Scan public trend sources</button> <span class="muted">Uses public RSS only. Respects robots.txt / rate limits.</span><div id="t_stat" class="muted"></div></div><div class="card"><table><tr><th>Trend</th><th>Source</th><th>Detected</th><th>Score</th><th>Signal</th><th>Platform</th><th>Angle</th><th></th></tr><tbody id="t_rows"></tbody></table></div><div class="card"><h3>Add custom RSS feed</h3><input id="t_add" placeholder="https://…/feed.xml"> <button id="t_addb">Add</button></div>`;
 const render=async()=>{const ts=await DB.recs('trend',Session.orgId);$('#t_rows').innerHTML=ts.slice(0,30).map(t=>`<tr><td>${esc(t.data.title.slice(0,80))}</td><td class="tiny">${esc(t.data.source)}</td><td class="tiny">${new Date(t.data.date).toLocaleDateString()}</td><td><b>${t.data.score}</b></td><td>${t.data.growth}</td><td>${t.data.platform}</td><td class="tiny">${esc(t.data.angle)}</td><td><button class="small gold" data-g="${t.id}">Generate</button></td></tr>`).join('')||'<tr><td colspan="8" class="muted">No trends yet — run a scan.</td></tr>';
  el.querySelectorAll('[data-g]').forEach(b=>b.onclick=async()=>{const t=await DB.get('records',b.dataset.g);location.hash='#/studio';setTimeout(()=>studio(document.getElementById('main'),{topic:t.data.title,pillar:'Education'}),120)})};
 $('#t_addb').onclick=async()=>{const s=await getSettings();s.feeds.push($('#t_add').value);await saveSettings(s);toast('Feed added','ok')};
 $('#t_scan').onclick=async e=>{e.target.disabled=true;$('#t_stat').textContent='Scanning…';const s=await getSettings();
  const q=(window.__org.business||{}).niche||'';const feeds=[...s.feeds];if(q)feeds.push('https://news.google.com/rss/search?q='+encodeURIComponent(q));
  let all=[];for(const f of feeds){all=all.concat(await fetchFeed(f))}
  const seen=new Set();all=all.filter(i=>{const k=i.title.toLowerCase();if(seen.has(k))return false;seen.add(k);return true});
  const scored=E.scoreTrends(window.__org,all);let n=0;
  for(const t of scored.slice(0,25)){await DB.putRec('trend',Session.orgId,t);n++}
  await notify(Session.orgId,'Trend scan complete',n+' trends ranked.');$('#t_stat').textContent=n+' trends ranked by relevance × freshness × growth.';
  e.target.disabled=false;render()};
 await render()}
// ---------- ACCOUNTS ----------
export async function accounts(el){const conns=await DB.recs('connection',Session.orgId);
 el.innerHTML=`<h1>Social Accounts</h1><div class="card"><button class="gold" id="a_meta">Connect Facebook (official OAuth)</button> <button class="ghost" id="a_li">Add LinkedIn token</button><p class="muted">We NEVER ask for social passwords. Tokens are encrypted (AES-GCM).</p></div>
 <div class="card"><table><tr><th>Platform</th><th>Account</th><th>Status</th><th>Capability</th><th>Last sync</th><th></th></tr>${conns.map(c=>`<tr><td>${P.PLATFORMS[c.platform].name}</td><td>${esc(c.name)}</td><td class="ok">${c.status}</td><td class="tiny">${esc(c.capability)}</td><td class="tiny">${c.lastSync?new Date(c.lastSync).toLocaleString():'—'}</td><td><button class="small red" data-dc="${c.id}">Disconnect</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">None connected.</td></tr>'}</table></div>
 <div class="card"><h3>Platform capability matrix</h3>${Object.entries(P.PLATFORMS).map(([k,v])=>`<div class="kv"><span><b>${v.name}</b> — ${esc(v.note)}</span><span class="pill ${v.auto?'safe':'review'}">${v.auto?'AUTO':'MANUAL ASSIST'}</span></div>`).join('')}</div>`;
 $('#a_meta').onclick=async e=>{e.target.disabled=true;try{await P.metaConnect();toast('Connected','ok');accounts(el)}catch(err){toast(err.message,'err');e.target.disabled=false}};
 $('#a_li').onclick=()=>openModal('LinkedIn access token',`<p class="muted">Create a free app at linkedin.com/developers → obtain a token with w_member_social scope. Stored encrypted; used only for verification — publishing uses the copy workflow because LinkedIn blocks browser API calls.</p><input id="li_t"><p><button class="gold" id="li_s">Save encrypted</button></p>`,()=>{$('#li_s').onclick=async()=>{const id=uid();await DB.putRec('secret',Session.orgId,await encJSONwrap($('#li_t').value),id);await DB.putRec('connection',Session.orgId,{platform:'linkedin',name:'LinkedIn (token)',secretId:id,status:'connected',capability:'manual assist (CORS-blocked API)'});closeModal();accounts(el)}});
 el.querySelectorAll('[data-dc]').forEach(b=>b.onclick=async()=>{await DB.del('records',b.dataset.dc);await audit(Session.orgId,'disconnect',b.dataset.dc);accounts(el)})}
async function encJSONwrap(v){const{encJSON}=await import('./core.js');return encJSON(Session.key,{token:v})}
// ---------- ANALYTICS ----------
export async function analytics(el){const posts=await DB.recs('schedule',Session.orgId);const pub=posts.filter(p=>p.status==='published');
 const withM=pub.filter(p=>p.metrics&&p.metrics.reach!=null);
 const totR=withM.reduce((s,p)=>s+(p.metrics.reach||0),0),totE=withM.reduce((s,p)=>s+(p.metrics.engagement||0),0);
 const sc=E.marketingScore(window.__org,posts);const an=E.analyzePerformance(window.__org,posts);
 el.innerHTML=`<h1>Analytics</h1><div class="grid g4"><div class="card"><h3>Reach</h3><div class="score">${totR||'—'}</div>${withM.length?'':'<span class="muted">Data unavailable</span>'}</div><div class="card"><h3>Engagement</h3><div class="score">${totE||'—'}</div></div><div class="card"><h3>Eng. rate</h3><div class="score">${totR?(totE/totR*100).toFixed(2)+'%':'—'}</div></div><div class="card"><h3>Marketing score</h3><div class="score">${sc.score}</div></div></div>
 <div class="card"><h3>How the score is calculated</h3>${sc.parts.map(p=>`<div class="kv"><span>${p.k} ${p.avail?'':'<span class="muted">(data unavailable — excluded)</span>'}</span><span>${Math.round(p.v)} · ${esc(p.why)}</span></div>`).join('')}</div>
 <div class="card"><h3>AI performance analysis</h3>${an.notes.map(n=>`<p>• ${esc(n)}</p>`).join('')}${an.general?'<p class="muted">Labelled general guidance — under 3 measured posts.</p>':''}</div>
 <div class="card"><h3>Posts</h3><table><tr><th>Post</th><th>Platform</th><th>Mode</th><th>Reach</th><th>Engagement</th><th>Log metrics</th></tr>${pub.map(p=>`<tr><td>${esc((p.hook||'').slice(0,50))}</td><td>${p.platform}</td><td class="tiny">${p.publishMode||'auto'}</td><td>${p.metrics&&p.metrics.reach!=null?p.metrics.reach:'<span class="muted">unavailable</span>'}</td><td>${p.metrics&&p.metrics.engagement!=null?p.metrics.engagement:''}</td><td><button class="small" data-m="${p.id}">+</button></td></tr>`).join('')||'<tr><td colspan="6" class="muted">Nothing published yet.</td></tr>'}</table></div>`;
 el.querySelectorAll('[data-m]').forEach(b=>b.onclick=async()=>{const p=await DB.get('records',b.dataset.m);openModal('Log metrics (from platform insights)',`<label>Reach</label><input type="number" id="mm_r"><label>Engagement</label><input type="number" id="mm_e"><p><button class="gold" id="mm_s">Save</button></p>`,()=>{$('#mm_s').onclick=async()=>{await DB.putRec('schedule',Session.orgId,Object.assign(p.data,{metrics:{reach:+$('#mm_r').value||0,engagement:+$('#mm_e').value||0,ts:nowISO(),manual:true}}),p.id);closeModal();analytics(el)}})})}
// ---------- MEDIA ----------
export async function media(el){const all=await DB.all('media');
 el.innerHTML=`<h1>Media Library</h1><div class="card"><input type="file" id="m_up" multiple accept="image/*,video/*,application/pdf"> <button class="gold" id="m_comp">Open Visual Composer</button></div><div class="grid g3">${all.map(m=>`<div class="card"><b class="tiny">${esc(m.name)}</b><br>${m.mime.startsWith('image')?`<img data-mu="${m.id}" style="max-width:100%;border-radius:8px" alt="">`:`<span class="muted">${m.mime}</span>`}<br><button class="small red" data-md="${m.id}">Delete</button></div>`).join('')||'<p class="muted">Empty.</p>'}</div>`;
 for(const im of el.querySelectorAll('[data-mu]'))im.src=await mediaURL(im.dataset.mu);
 $('#m_up').onchange=async e=>{for(const f of e.target.files)await saveMedia(f);toast('Uploaded','ok');media(el)};
 $('#m_comp').onclick=()=>composeModal({platform:'instagram',topic:'',cta:null});
 el.querySelectorAll('[data-md]').forEach(b=>b.onclick=async()=>{await DB.del('media',b.dataset.md);media(el)})}
// ---------- BRAND / PRODUCTS / AUDIENCE / CAMPAIGNS ----------
export async function brand(el){const b=window.__org.brand||{};const bus=window.__org.business||{};
 el.innerHTML=`<h1>Brand Kit</h1><div class="card"><div style="display:flex;gap:10px;align-items:center"><span style="width:40px;height:40px;background:${(b.colours||{}).primary||'#0e2a5c'};border-radius:8px"></span><span style="width:40px;height:40px;background:${(b.colours||{}).secondary||'#c9a227'};border-radius:8px"></span><img src="assets/logo.png" style="height:44px" alt="logo"></div>
 ${fld([['slogan','Slogan'],['voice','Brand voice'],['personality','Personality'],['tone','Tone',0,'select',['professional','friendly','bold','playful','empathetic']],['useWords','Use words'],['avoidWords','Avoid words']],b)}<button class="gold" id="b_s">Save</button></div>`;
 $('#b_s').onclick=async()=>{const o=await DB.rec('org',Session.orgId);const d=o.data;d.brand=Object.assign(d.brand||{},readAll(el,['slogan','voice','personality','tone','useWords','avoidWords']));await DB.put('records',o);await setOrgCache();toast('Brand saved','ok')}}
function readAll(root,keys){const o={};keys.forEach(k=>{const i=root.querySelector(`[name=${k}]`);if(i)o[k]=i.value});return o}
export async function products(el){const list=await DB.recs('product',Session.orgId);
 el.innerHTML=`<h1>Products & Services</h1><div class="card"><button class="gold" id="p_new">+ Add</button></div>${list.map(p=>`<div class="card"><b>${esc(p.data.name)}</b> <span class="muted">${esc(p.data.category||'')}</span> <span class="badge">${esc(p.data.price||'')}</span><p class="muted">${esc((p.data.description||'').slice(0,160))}</p><button class="small" data-e="${p.id}">Edit</button> <button class="small red" data-d="${p.id}">Delete</button> <button class="small gold" data-pr="${p.id}">Promote</button></div>`).join('')||'<div class="card muted">No products yet.</div>'};
 const edit=async id=>{const p=id?(await DB.get('records',id)).data:{};openModal('Product',fld([['name','Name',1],['description','Description',0,'textarea'],['category','Category'],['price','Price'],['currency','Currency'],['features','Features',0,'textarea'],['benefits','Benefits',0,'textarea'],['target','Target customer'],['problems','Problems solved',0,'textarea'],['usp','USP'],['url','Purchase URL'],['allowedClaims','Allowed claims',0,'textarea'],['forbiddenClaims','Forbidden claims',0,'textarea']],p)+`<button class="gold" id="p_s">Save</button>`,()=>{$('#p_s').onclick=async()=>{await DB.putRec('product',Session.orgId,Object.assign(p,readAll(document,['name','description','category','price','currency','features','benefits','target','problems','usp','url','allowedClaims','forbiddenClaims'])),id||undefined);closeModal();await setOrgCache();products(el)}})};
 $('#p_new').onclick=()=>edit();
 el.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>edit(b.dataset.e));
 el.querySelectorAll('[data-d]').forEach(b=>b.onclick=async()=>{await DB.del('records',b.dataset.d);products(el)});
 el.querySelectorAll('[data-pr]').forEach(b=>b.onclick=async()=>{const p=await DB.get('records',b.dataset.pr);location.hash='#/studio';setTimeout(()=>studio($('#main'),{product:p.data,topic:p.data.name,pillar:'Promotional'}),120)})}
export async function audience(el){const per=await DB.recs('persona',Session.orgId);const com=await DB.recs('competitor',Session.orgId);
 el.innerHTML=`<h1>Audience</h1><div class="grid g2"><div class="card"><h3>Personas</h3>${per.map(p=>`<div class="kv"><span>${esc(p.data.name)}</span><button class="small red" data-d="${p.id}">✕</button></div>`).join('')}<input id="a_p" placeholder="New persona"><button id="a_pa">Add</button></div><div class="card"><h3>Competitors</h3>${com.map(p=>`<div class="kv"><span>${esc(p.data.name)}</span><button class="small red" data-d="${p.id}">✕</button></div>`).join('')}<input id="a_c" placeholder="New competitor"><button id="a_ca">Add</button></div></div>`;
 $('#a_pa').onclick=async()=>{await DB.putRec('persona',Session.orgId,{name:$('#a_p').value});audience(el)};
 $('#a_ca').onclick=async()=>{await DB.putRec('competitor',Session.orgId,{name:$('#a_c').value});audience(el)};
 el.querySelectorAll('[data-d]').forEach(b=>b.onclick=async()=>{await DB.del('records',b.dataset.d);audience(el)})}
export async function campaigns(el){const list=await DB.recs('campaign',Session.orgId);
 el.innerHTML=`<h1>Campaigns</h1><div class="card"><button class="gold" id="c_new">+ New campaign</button></div>${list.map(c=>`<div class="card"><b>${esc(c.data.name)}</b> <span class="badge">${esc(c.data.objective||'')}</span><p class="muted">${esc(c.data.start||'')} → ${esc(c.data.end||'')} · platforms: ${(c.data.platforms||[]).join(', ')}</p><button class="small gold" data-plan="${c.id}">AI campaign plan</button> <button class="small red" data-d="${c.id}">Delete</button></div>`).join('')||'<div class="card muted">No campaigns.</div>'}`;
 $('#c_new').onclick=()=>openModal('New campaign',fld([['name','Name',1],['objective','Objective',0,'select',['awareness','leads','sales','traffic']],['start','Start'],['end','End'],['frequency','Posts/week',0,'number'],['kpi','KPI targets']],{})+`<button class="gold" id="c_s">Save</button>`,()=>{$('#c_s').onclick=async()=>{const d=readAll(document,['name','objective','start','end','frequency','kpi']);d.platforms=(window.__org.marketing||{}).platforms||['facebook'];await DB.putRec('campaign',Session.orgId,d);closeModal();campaigns(el)}});
 el.querySelectorAll('[data-plan]').forEach(b=>b.onclick=async()=>{const c=await DB.get('records',b.dataset.plan);const posts=await DB.recs('schedule',Session.orgId);
  const plan=E.buildPlan(window.__org,posts,7).map(s=>Object.assign(s,{campaign:c.data.name}));let n=0;
  for(const s of plan){const r=await genContent(window.__org,{platform:s.platform,pillar:s.pillar,topic:s.topic,tone:'professional',product:(window.__org.products||[])[0]||null,cta:(window.__org.ctas||[])[0]||null});
   await DB.putRec('schedule',Session.orgId,{platform:s.platform,pillar:s.pillar,topic:s.topic,hook:r.out.hook,caption:r.out.caption,hashtags:r.out.hashtags,status:'needs_review',scheduledAt:s.scheduledAt,campaign:c.data.name,createdAt:nowISO()});n++}
  toast(`Campaign plan: ${n} drafts in approval queue`,'ok')});
 el.querySelectorAll('[data-d]').forEach(b=>b.onclick=async()=>{await DB.del('records',b.dataset.d);campaigns(el)})}
// ---------- AUTOMATION ----------
export async function automation(el){const s=await getSettings();const due=await P.postsDue(Session.orgId);const jobs=(await DB.recs('joblog',Session.orgId)).slice(-12).reverse();
 el.innerHTML=`<h1>Automation</h1><div class="card"><h3>Automation level</h3>${[1,2,3,4].map(l=>`<label style="font-weight:400"><input type="radio" name="lv" value="${l}" style="width:auto" ${s.automationLevel===l?'checked':''}> <b>L${l}</b> — ${['AI suggestions only','AI generates drafts','AI schedules after your approval','AI auto-publishes approved content (Facebook only)'][l-1]}</label><br>`).join('')}<button class="gold" id="au_s">Save</button> <span class="muted">Higher levels require explicit opt-in. Human-in-the-loop by default.</span></div>
 <div class="card"><h3>Publish queue (${due.length} due)</h3>${due.map(p=>`<div class="kv"><span>${p.platform} · ${esc((p.hook||'').slice(0,60))}</span><span><button class="small gold" data-pb="${p.id}">Publish</button> <button class="small ghost" data-rs="${p.id}">+1h</button></span></div>`).join('')||'<p class="muted">Nothing due.</p>'}</div>
 <div class="card"><h3>Job log</h3><table><tr><th>Job</th><th>Status</th><th>Detail</th><th>When</th></tr>${jobs.map(j=>`<tr><td>${j.data.job}</td><td class="${j.data.status==='ok'?'ok':'err'}">${j.data.status}</td><td class="tiny">${esc(j.data.detail||'')}</td><td class="tiny">${new Date(j.ts).toLocaleTimeString()}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">No jobs yet.</td></tr>'}</table></div>`;
 $('#au_s').onclick=async()=>{s.automationLevel=+el.querySelector('[name=lv]:checked').value;await saveSettings(s);await audit(Session.orgId,'automation_level',s.automationLevel);toast('Saved','ok')};
 el.querySelectorAll('[data-pb]').forEach(b=>b.onclick=async()=>{const p=await DB.get('records',b.dataset.pb);await publishFlow(p);automation(el)});
 el.querySelectorAll('[data-rs]').forEach(b=>b.onclick=async()=>{const p=await DB.get('records',b.dataset.rs);const t=new Date(Date.now()+3600e3);await DB.putRec('schedule',Session.orgId,Object.assign(p.data,{status:'scheduled',scheduledAt:t.toISOString()}),p.id);automation(el)})}
// ---------- SETTINGS / ADMIN / HELP ----------
export async function settings(el){const s=await getSettings();
 el.innerHTML=`<h1>Settings</h1><div class="grid g2"><div class="card"><h3>AI provider</h3><label>Provider</label><select id="g_prov"><option value="offline" ${s.ai.provider==='offline'?'selected':''}>Offline rules engine (always available)</option><option value="ollama" ${s.ai.provider==='ollama'?'selected':''}>Ollama (local, free)</option><option value="compat" ${s.ai.provider==='compat'?'selected':''}>OpenAI-compatible free endpoint</option></select><label>Ollama URL</label><input id="g_ou" value="${esc(s.ai.ollamaUrl)}"><label>Ollama model</label><input id="g_om" value="${esc(s.ai.model)}"><label>Compat URL</label><input id="g_cu" value="${esc(s.ai.compatUrl)}"><label>Compat key</label><input id="g_ck" type="password" value="${esc(s.ai.compatKey)}"><label>Compat model</label><input id="g_cm" value="${esc(s.ai.compatModel)}"><button id="g_ping">Test connection</button></div>
 <div class="card"><h3>Integrations & prefs</h3><label>Meta App ID (enables FB publishing)</label><input id="g_ma" value="${esc(s.metaAppId)}"><label>Timezone</label><input id="g_tz" value="${esc(s.tz)}"><label>Banned hashtags (comma)</label><input id="g_bh" value="${esc(((window.__org.marketing||{}).bannedHashtags||[]).join(', '))}"><label style="font-weight:400"><input type="checkbox" id="g_bn" style="width:auto" ${s.browserNotify?'checked':''}> Browser notifications</label><button class="gold" id="g_s">Save all</button></div>
 <div class="card"><h3>Security</h3><button id="g_cp">Change passcode</button></div>
 <div class="card"><h3>Privacy</h3><button id="g_ex">Export my data (JSON)</button> <button class="red" id="g_del">Delete organisation data</button><p class="muted">Data never leaves this device except to APIs you connect.</p></div></div>`;
 $('#g_ping').onclick=async()=>{try{const r=await fetch(s.ai.provider==='compat'?s.ai.compatUrl||$('#g_cu').value:($('#g_ou').value||s.ai.ollamaUrl)+'/api/tags');toast(r.ok?'AI reachable ✔':'Unreachable — offline engine will be used',r.ok?'ok':'err')}catch(e){toast('Unreachable — offline engine will be used','err')}};
 $('#g_s').onclick=async()=>{const n={ai:{provider:$('#g_prov').value,ollamaUrl:$('#g_ou').value,model:$('#g_om').value,compatUrl:$('#g_cu').value,compatKey:$('#g_ck').value,compatModel:$('#g_cm').value},metaAppId:$('#g_ma').value,tz:$('#g_tz').value,browserNotify:$('#g_bn').checked,feeds:s.feeds,automationLevel:s.automationLevel};await saveSettings(n);
  const o=await DB.rec('org',Session.orgId);o.data.marketing=Object.assign(o.data.marketing||{},{bannedHashtags:$('#g_bh').value.split(',').map(x=>x.trim()).filter(Boolean)});await DB.put('records',o);
  if($('#g_bn').checked&&'Notification'in window)Notification.requestPermission();await setOrgCache();toast('Saved','ok')};
 $('#g_cp').onclick=()=>openModal('Change passcode',`<label>New passcode</label><input type="password" id="cp_n" minlength="8"><p><button class="gold" id="cp_s">Update</button></p>`,()=>{$('#cp_s').onclick=async()=>{const sec=await DB.get('records','auth');const{hashPass:hp,makeKey:mk}=await import('./core.js');sec.data.salt=uid();sec.data.hash=await hp($('#cp_n').value,sec.data.salt);await DB.put('records',sec);Session.key=await mk($('#cp_n').value,sec.data.salt);closeModal();toast('Passcode updated','ok')}});
 $('#g_ex').onclick=async()=>{const all=(await DB.all('records')).filter(r=>r.orgId===Session.orgId||r.id==='settings');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(all,null,1)],{type:'application/json'}));a.download='tradestack-export.json';a.click()};
 $('#g_del').onclick=async()=>{if(confirm('Delete ALL data for this organisation?')){await DB.delOrg(Session.orgId);Session.orgId=null;ls.set('org',null);location.reload()}}}
export async function admin(el){const all=await DB.all('records');const aud=(await DB.recs('audit',Session.orgId)).slice(-15).reverse();const est=await navigator.storage.estimate();
 const s=await getSettings();let ai='offline';try{if(s.ai.provider==='ollama'){const r=await fetch(s.ai.ollamaUrl+'/api/tags');ai=r.ok?'ollama ✔':'ollama ✘ (fallback active)'}else ai=s.ai.provider}catch(e){ai+=' (fallback active)'}
 el.innerHTML=`<h1>Admin</h1><div class="grid g3"><div class="card"><h3>System health</h3><div class="kv"><span>Records</span><span>${all.length}</span></div><div class="kv"><span>Storage used</span><span>${Math.round((est.usage||0)/1024)} KB</span></div><div class="kv"><span>AI provider</span><span>${esc(ai)}</span></div><div class="kv"><span>Automation</span><span>L${s.automationLevel}</span></div></div>
 <div class="card"><h3>Audit log</h3>${aud.map(a=>`<div class="kv"><span>${esc(a.data.action)}</span><span class="tiny">${new Date(a.ts).toLocaleTimeString()}</span></div>`).join('')||'<p class="muted">Empty.</p>'}</div>
 <div class="card"><h3>Feature flags</h3><div class="kv"><span>Manual metrics logging</span><span class="ok">on</span></div><div class="kv"><span>Trend scanning</span><span class="ok">on</span></div><div class="kv"><span>Auto-publish (L4)</span><span>${s.automationLevel>=4?'<span class="ok">on</span>':'off'}</span></div></div></div>`}
export async function help(el){el.innerHTML=`<h1>Help & Legal</h1><div class="card"><p>• AI-generated content requires human review. You are responsible for claims and published content.<br>• Platform API capabilities change; automated publishing depends on permissions you grant.<br>• Growth is never guaranteed; trend data may be incomplete.<br>• Regulated claims (health/financial) require your verification — the compliance engine flags them but you decide.<br>• We never store social passwords, never scrape behind logins, never spam, never fake engagement.</p></div><div class="card"><h3>Quick guide</h3><p>Onboarding → add products → connect Facebook → Trends (scan) → Studio (generate) → Calendar (approve) → Automation (publish queue). Ask the AI Agent anything from the Dashboard.</p></div>`}
// ---------- ASSISTANT ----------
export async function assistant(el){el.innerHTML=`<h1>AI Marketing Agent</h1><div class="card"><div class="chat" id="ch"></div><form id="cf" style="display:flex;gap:8px;margin-top:10px"><input id="ci" placeholder="What would you like to market today?" aria-label="Message the agent"><button class="gold">Send</button></form></div>`;
 const hist=await DB.recs('conversation',Session.orgId);hist.slice(-20).forEach(h=>addMsg(h.data.role,h.data.text));
 $('#cf').onsubmit=e=>{e.preventDefault();assistantAsk($('#ci').value);$('#ci').value=''}};
function addMsg(role,text){const c=$('#ch');if(!c)return;const d=document.createElement('div');d.className='msg '+role;d.textContent=text;c.appendChild(d);c.scrollTop=c.scrollHeight}
export async function assistantAsk(q){if(!q)return;addMsg('u',q);await DB.putRec('conversation',Session.orgId,{role:'u',text:q});
 const org=window.__org;const posts=await DB.recs('schedule',Session.orgId);let out='';
 const L=q.toLowerCase();
 if(L.includes('week')&&L.includes('content')||L.includes('calendar')){const plan=E.buildPlan(org,posts,7);let n=0;
  for(const s of plan){const r=await genContent(org,{platform:s.platform,pillar:s.pillar,topic:s.topic,tone:(org.brand||{}).tone||'professional',product:(org.products||[])[0]||null,cta:(org.ctas||[])[0]||null});
   await DB.putRec('schedule',Session.orgId,{platform:s.platform,pillar:s.pillar,topic:s.topic,hook:r.out.hook,caption:r.out.caption,hashtags:r.out.hashtags,status:'needs_review',scheduledAt:s.scheduledAt,createdAt:nowISO()});n++}
  out=`I created ${n} draft posts in your approval queue (Content Calendar). Nothing publishes without your approval.`}
 else if(L.includes('trend')){location.hash='#/trends';out='Opening Trends — run a scan; I rank by relevance × freshness × growth from public RSS only.'}
 else if(L.includes('promote')){const p=(org.products||[])[org.products.length-1];out=p?'Opening Content Studio pre-filled with '+p.name+'.':'Add a product first (Products & Services).';location.hash='#/studio'}
 else if(L.includes('analy')){const a=E.analyzePerformance(org,posts);out=a.notes.join('\n')+(a.general?' (General guidance — not enough measured data yet.)':'')}
 else if(L.includes('best time')){const bt=E.bestTimes('facebook',posts);out=`Recommended window: ${bt.top[0].day} ${bt.top[0].hour}:00 (score ${bt.top[0].score}). Confidence: ${bt.top[0].confidence}. Never universal — it improves as your data grows.`}
 else{try{const r=await aiChat(org,q,false);out=r||fallback(q)}catch(e){out=fallback(q)}}
 addMsg('a',out);await DB.putRec('conversation',Session.orgId,{role:'a',text:out});await setOrgCache()}
function fallback(q){return 'No AI provider reachable, and I have no offline rule for that request. I will not pretend to have done something I did not. Options: set up Ollama in Settings (free, local), or use Content Studio\u2019s built-in offline engine which always works.'}
